// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIZKtz6OTbqEMclTiKHZj9G4wV8vHzIWc',
    appId: '1:915457394725:android:f779747f97d144435817cc',
    messagingSenderId: '915457394725',
    projectId: 'war-second-wind',
    storageBucket: 'war-second-wind.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3wHgZ-k43QbS0nPFzSO5PfkA3kVHj-zY',
    appId: '1:915457394725:web:1ca30a997fec56ee5817cc',
    messagingSenderId: '915457394725',
    projectId: 'war-second-wind',
    authDomain: 'war-second-wind.firebaseapp.com',
    storageBucket: 'war-second-wind.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD70rKPbSQ6Zrls0ZOFj7j2uW36irDQ7s4',
    appId: '1:915457394725:ios:4d34b46ed72e14e15817cc',
    messagingSenderId: '915457394725',
    projectId: 'war-second-wind',
    storageBucket: 'war-second-wind.firebasestorage.app',
    iosBundleId: 'icu.sunshade.warsecondwind',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD70rKPbSQ6Zrls0ZOFj7j2uW36irDQ7s4',
    appId: '1:915457394725:ios:4d34b46ed72e14e15817cc',
    messagingSenderId: '915457394725',
    projectId: 'war-second-wind',
    storageBucket: 'war-second-wind.firebasestorage.app',
    iosBundleId: 'icu.sunshade.warsecondwind',
  );
}
